# Generated by Django 6.0.1 on 2026-01-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuiaMuseo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        max_length=200, verbose_name="Nombres y Apellidos"
                    ),
                ),
                (
                    "anos_experiencia_guia",
                    models.IntegerField(verbose_name="Años de Experiencia"),
                ),
                (
                    "idiomas_hablados",
                    models.CharField(help_text="Ej: Español, Inglés", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Museo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre del Museo"
                    ),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "anio_fundacion",
                    models.IntegerField(verbose_name="Año de Fundación"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exhibicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_exhibicion",
                    models.CharField(max_length=200, verbose_name="Título"),
                ),
                (
                    "duracion_meses",
                    models.IntegerField(verbose_name="Duración (meses)"),
                ),
                (
                    "costo_produccion",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo Producción"
                    ),
                ),
                ("tematica", models.CharField(max_length=200, verbose_name="Temática")),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="museos.guiamuseo",
                        verbose_name="Guía Asistente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guiamuseo",
            name="museo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guias",
                to="museos.museo",
            ),
        ),
    ]
